### ISSUE TITLE
Complete mock ContactsScreen screen

### ISSUE THREAD

**Issue by HunnySajid** [roots-id/roots-react-native#1]
# Value: $200

# Screens to cover

- [x] Contact Screen

### Features:

As a user, I want to navigate the app by creating a wallet, login in, and viewing our contacts
@2byrds will add the RootsWallet [RelationshipScreen](https://github.com/roots-id/rootswallet/blob/main/src/screens/RelationshipsScreen.js) to the project.
@2byrds will rename the screen to ContactsScreen
@HunnySajid will modify the navigation of the login screen to navigate to the ContactsScreen
@HunnySajid will mock the data necessary for the Contact screen to, so that it has 3 fake contacts.
The fake contacts will be (Guest, Esteban, Rodolfo, and MeGrimLance)
It should look like:
<img width="357" alt="image" src="https://user-images.githubusercontent.com/681493/194059066-8b007c6b-17e3-4d6c-89a9-f6e328bf4b16.png">

**Comment by 2byrds** [comment]
I'm looking forward to an update on your progress.  How's it going @HunnySajid ?

**Comment by 2byrds** [comment]
@HunnySajid I have updated this ticket to be more specific to a single screen.  If we complete this together, we can move onto the next screen.

**Comment by 2byrds** [comment]
@HunnySajid I have given you write access to the repo so that you can develop in a branch and we can work from this project together

**Comment by 2byrds** [comment]
@HunnySajid I see some of the work you did here https://github.com/HunnySajid/roots-react-native/commit/cd56f54eb4ff800ab0ce32a0e6c088b5f0d360b0 good start!
I think the setup of the repository that I did will simplify things greatly for you.

**Comment by HunnySajid** [comment]
@2byrds I am about to finish this, will create an MR shortly.

**Comment by 2byrds** [comment]
Great work!  PR accepted, i'll create the next issue for us.
