### ISSUE TITLE
Review missing mocks

### ISSUE THREAD

**Issue by 2byrds** [roots-id/roots-react-native#11]
Our current roots-react-native mocks are a great start.
We need to catch-up with the rest of the RootsWallet UI.
Eventually roots-react-native will always be ahead of RootsWallet, as we will iterate all UI changes here first (after figma mocks).

@AlexAndrei98 has completed several mocks that show existing and future UI features/modals/pages.
He will close his tickets in the other repos and post the links to those mocks on this ticket so that @HunnySajid can review them and ask questions, etc.

- [x] Review the figma mocks that @AlexAndrei98 and I post here and ask questions
- [x] Comment here with the list of features we are still missing
- [x] Lets negotiate what we can add for this next 2 week period so I can get the work approved for another $1000
- [x] We will create the issues needed based on what is missing and what we prioritize first.

**Comment by 2byrds** [comment]
@HunnySajid take a look at the animatedGifs and vids here to see some of the parts we are still missing (most of it should already look faimiliar) https://drive.google.com/drive/folders/1ah7o1HoPL05ien6Z30tAN9aKE0tgKST0?usp=sharing
For instance we need:

- the QR Code modal from RootsWallet
- we need to the barcode scanner model from RootsWallet
- we need the verify button (question mark) on the credential detail to turn into a check mark or x mark (perhaps alternate in our mock screen)
- we have a task in RootsWallet to be able to see info about all operations (like tooltips, but for mobile)
- etc.

Also you can take a look at our settings screen and import/export modal https://youtu.be/6y_d2rTyoY4

**Comment by HunnySajid** [comment]
@2byrds Sure, I will take a look today and reach out with feedback.

**Comment by HunnySajid** [comment]
@2byrds
I went through the mockup, it looks great. 
**A quick question** -- are we going to follow the one with white/light theme or sticking with the old/black theme for now?

Here is the list:
- Setting Screen
- Ability to approve/ review verified credentials
- QR code modal
- Scan QR code modal
- What happens when a credential is revoked?

I need some clarity on the following:
- What happens when a credential is revoked in terms of UX
- Number of entities involved, I think there are three main entities a user, a protocol (prism in this case), a mediator (rootsId)

Let's create some issues regarding the missing screens mentioned above and we can finish these before moving forward with the next. What do you say?

**Comment by 2byrds** [comment]
Sounds great!
For now, when thinking about a credential being revoked, think of a driver's license.  If the expiration date is in the past, the license is no longer valid.
So think of it as a simple call that returns a boolean, 'is this valid?' yes/no.
I'll create those tickets.

**Comment by 2byrds** [comment]
@HunnySajid as for the entities involved.  Because this is a self-sovereign identity (some call it Web5) there are three main roles:

- Holder (the mobile wallet containing ALL of your digital identity information like licenses, education credentials, passport, medical records, etc).  A holder might use a mediator as a communication relay with the rest of the internet.
- Issuer who issues licenses, edu creds, passport, medical records.  They also have some of your identity information, since that is how they issue verifiable credentials to you.  And they can have their own identity wallet as well, although likely on a server or in the cloud.  But currently issuers, like our doctors, have our medical records.... in self-soveriegn identity, you both have the medical records and the issuer has no more information about you than they need in order to provide you medical credentials.
- Verifier is anyone who is verifying your credentials in order to provide you some service or access.  For instance your university might require a graduation certificate from you lower-education.  In that case your university is verifying your credential.  they might also ask for your id card to verify you are Hunny.  They should only be getting enough information from the holder to process the service/access.

In our app.  The holder sees other holders, verifiers, issuers as contacts.  The chat view is a log of all of the transactions between you and them.  And the credentials are all of the credentials you have been given or sent (in which case you are acting as an issuer).

thats a good start for now.  happy to discuss more on a call.

**Comment by 2byrds** [comment]
Regarding white theme, @AlexAndrei98 had presented that to us. We haven't said yes/no.  My initial comment was that dark themes rule nowadays.  But we'd love your input too @HunnySajid.  Colors aside, one thing I'm challenging us to do is avoid pages.  To keep the UX contact/chat/credential based. previous wallets have many pages and we are trying to use richchat and workflows instead.  We would love to discuss more soon.  But not quite yet, we still need to get the current mock complete so we can start iterating changes that can be incorporated into RootsWallet easily
