### ISSUE TITLE
Add Settings Screen

### ISSUE THREAD

**Issue by 2byrds** [roots-id/roots-react-native#12]
It should look like the RootsWallet Settings screen

https://user-images.githubusercontent.com/681493/196707356-36e15220-88df-4d2a-a31c-4a0835f47d5c.mov

https://github.com/roots-id/rootswallet/blob/main/src/screens/SettingsScreen.tsx

**Comment by 2byrds** [comment]
You should be able to get to the settings screen from every screen (either the Settings Button or the Cog symbol)

**Comment by HunnySajid** [comment]
Hey @2byrds ,
I am working on this one, you can add the rest of the tickets. I'll pick up as soon as I am done with this.

**Comment by 2byrds** [comment]
Sorry @HunnySajid I meant to create the whole batch but got pulled into a meeting.  I'll create them soon

**Comment by HunnySajid** [comment]
@2byrds  you can review and roll out this one.

**Comment by 2byrds** [comment]
Great work by @HunnySajid https://github.com/roots-id/roots-react-native/pull/15
