### ISSUE TITLE
Create QR Code Modal

### ISSUE THREAD

**Issue by 2byrds** [roots-id/roots-react-native#13]
Create a mock data QR Code Modal based on the one we use in RootsWallet.
https://github.com/roots-id/rootswallet/blob/main/src/screens/ShowQRCodeScreen.js

It should be able to show a QR Code for a URL, some JSON data, etc.
This allows us to bootstrap sharing a contact, a credential, or to make a communication connection.

Here is a good demonstration of us connecting two RootsWallets with QR Codes connection information
https://drive.google.com/file/d/1r3AEcvUMGBoZmV-ys-6u3jzWGa0rKfvy/view?usp=sharing

Note, that in these two videos i'm using an emulator with an emulated scan (so you don't actually scan a barcode)..... that is because on my machine i'm having trouble using my webcam or virtualscene for my scanner.
The video where Rodolfo uses the scanner to scan bar codes is better.
But in my emulator, I show that if RootsWallet doesn't scan a barcode, and is in demo mode, the scanner will notify the user that a barcode wasn't scanned but a demo contact or credential is created for them. We should have similar functionality in our mock. See videos for contact and credential here:
https://user-images.githubusercontent.com/681493/197020555-2bcdd70b-d1db-49b3-877e-52ca3dd7e54c.mov
https://user-images.githubusercontent.com/681493/197020569-e90662a6-d973-4414-929c-34604f860610.mov

**Comment by HunnySajid** [comment]
@2byrds 
I was unable to use react-native-qrcode-svg on ios as it throws exception, looking into this right now.
It is working fine on web and android.

Also I have improved code structure a bit. Introduced redux/toolkit and redux-persist. We will handle all out data and states in redux store moving forward.

**Comment by 2byrds** [comment]
@HunnySajid thank you for the update.  Let's talk redux soon since I'm not familiar.  It looks promising.

**Comment by 2byrds** [comment]
@HunnySajid well done!  looking forward to chatting about Redux and next steps soon.
