### ISSUE TITLE
Create barcode scanner modal

### ISSUE THREAD

**Issue by 2byrds** [roots-id/roots-react-native#14]
Create a modal that mimics the RootsWallet barcode scanning modal.
https://github.com/roots-id/rootswallet/blob/main/src/screens/ScanQRCodeScreen.tsx

Note, that in these two videos i'm using an emulator with an emulated scan (so you don't actually scan a barcode)..... that is because on my machine i'm having trouble using my webcam or virtualscene for my scanner. 
The video where Rodolfo uses the scanner to scan bar codes is better.
But in my emulator, I show that if RootsWallet doesn't scan a barcode, and is in demo mode, the scanner will notify the user that a barcode wasn't scanned but a demo contact or credential is created for them.  We should have similar functionality in our mock.  See videos for contact and credential here:
https://user-images.githubusercontent.com/681493/197020555-2bcdd70b-d1db-49b3-877e-52ca3dd7e54c.mov
https://user-images.githubusercontent.com/681493/197020569-e90662a6-d973-4414-929c-34604f860610.mov

And see Rodolfo's video here:
https://drive.google.com/file/d/1r3AEcvUMGBoZmV-ys-6u3jzWGa0rKfvy/view?usp=sharing

**Comment by HunnySajid** [comment]
@2byrds  the barcode scanner package we are using does not work on web. It is working fine on ios,android though. 
What to you say should I look for an alternate for its good for now?

Rest functionality is done in the PR

**Comment by 2byrds** [comment]
@HunnySajid  is there a web one that you can easily use if you detect web platform?

**Comment by 2byrds** [comment]
@HunnySajid impressive improvements, thank you!
