### ISSUE TITLE
Mock issuing a credential to a contact and having the option to revoke it

### ISSUE THREAD

**Issue by 2byrds** [roots-id/roots-react-native#18]
See this older video for an example where we issued ourself a credential, and had a message that would allow us to revoke it.
Using Redux we should be able to maintain the state of the credentials we created.
Start at 1:00 in this video for an example https://youtu.be/666UCwT9Alw
However, instead of issuing ourself a credential, whenever we add a contact, the contact chat should have a message that gives us the option of issuing them a business card credential... and another message that says we issued it, with a button that allows us to revoke it.

Note that in our Credential List view, an issued credential shows up on the opposite side from the credentials that we've been given.... in the future we can work on ways of differentiating/separating credentials.

**Comment by HunnySajid** [comment]
@2byrds 
Wanted to update you about the progress. 
I am still working on this issue along with [issue-16](https://github.com/roots-id/roots-react-native/issues/16).
Will be done atmost by tomorrow.

**Comment by 2byrds** [comment]
@HunnySajid fantastic! It's busy here in Dubai, but I should be able to review it, etc.  Looking forward to it.  @AlexAndrei98 is working on some issue credential related work in RootsWallet so he should take a look and make comments as well.

**Comment by AlexAndrei98** [comment]
@HunnySajid Let me know if there is an issue creating credentials. I was able to implement a react native way to create some demo ones that conform to the standards. Also if there is any code you want me to run or test just let me know which branch and I can pull it!

**Comment by HunnySajid** [comment]
Hey @AlexAndrei98 
Thanks for the help. I was busy creating some underlying structure for dummy wallet -> contact -> chat correlation. The work is almost finished, I will raise an MR today.

**Comment by 2byrds** [comment]
@AlexAndrei98 can you post the Discord Social Credential diagrams you did, here.  If we can get that mock into this project then I can submit for additional milestone completion/funding.  @HunnySajid when Alex posts that we can decide if that should be a separate issue or include it here.

**Comment by AlexAndrei98** [comment]
<img width="410" alt="Screen Shot 2022-11-04 at 9 17 18 AM" src="https://user-images.githubusercontent.com/5164910/199997628-00e2d522-74ec-4b36-baea-adc04ab75964.png">
This is what I had mocked up and the idea was that the green check appears after you click the 'document' icon that does some verification. And the idea behind
 the qr code is that once you click on it it creates a "verifiable presentation" that can be checked by anyone else as well!

**Comment by 2byrds** [comment]
I had forgotten how much I like that :)

**Comment by HunnySajid** [comment]
Hey Alex,

I will check it out, it might reduce my work. Can you share the branch
where I can look at it?

**Comment by 2byrds** [comment]
@HunnySajid I don't think he's implemented it.  But I wanted you to be aware of his mock so that we can add it to roots-react-native as soon as you think we are ready.  It is a deliverable for a customer that we'd like to show them  since it the mock will get us some payment

**Comment by 2byrds** [comment]
For now revocation is based on even/odd credentials and that's okay.  we have a new ticket for the Discord credential.
