### ISSUE TITLE
Remove Create Wallet and Login screens - user chat narration instead

### ISSUE THREAD

**Issue by 2byrds** [roots-id/roots-react-native#22]
We don't need a create wallet page and login page.
We need to use narrated messages in the user chat that guides them to basic usage.

- [x] Remove Auth Screens
- [x] Update user messages
- [x] Update Settings to set avatar/name/protected-pin
- [x] Change splash bg
- [x] Add icons in messages

**Comment by 2byrds** [comment]
@HunnySajid here is a mock up.  Let me know what you think and what questions you have.
https://docs.google.com/presentation/d/17Kc0G5dyXOuv4fUQEa9GAe0loyIE-I1xpI-rlazrzCc/edit?usp=sharing
I decided to ignor the wallet recovery stuff for now.  lets keep it simpler.

**Comment by HunnySajid** [comment]
@2byrds  Looks good to me, just not sure about the "settings" and "back icon" within the message. Are we going to make /use ascii representations for these like in emojis? 
The profile avatar/ pincode thing is acknowledged, I will add those to user settings.

**Comment by 2byrds** [comment]
@HunnySajid yea emojis or something like it might be the best we can do.  i leave it to you to figure out how best to indicate visual portions of our interface in these helper messages.  thank you!

**Comment by 2byrds** [comment]
Great job Hunny!
