### ISSUE TITLE
Demonstrate DIDComm in swift for ios

### ISSUE THREAD

**Issue by 2byrds** [roots-id/roots-react-native#47]
SICPA react native library

**Comment by 2byrds** [comment]
pod installed the didcomm-rust from sicpa git. used arch x64 flag.
code will be posted to rootswallet.

**Comment by rodolfomiranda** [comment]
I push all changes to branch [demo-atp2](https://github.com/roots-id/rootswallet/tree/demo-atp2) on rootswallet repo, including:
- SICPA libraries as native modules on iOS and Android
- Peer DID creation and resolution in TypeScript
- Peer DID resolution in swift (own code) and Android (sicpa)
- Protocols are isolated from Operating System. Adding/changind DIDComm protocols and workflows should work for both iOS and Android seenlesly
- Test: Android device and iOS device, using rootsID mediator, sends basic message between them. [Demo video on Discord](https://discord.com/channels/922882385769533440/1012813656498638949/1072198332245618749)
