### ISSUE TITLE
Try SICPA libs in RN 68 project that uses a submodule

### ISSUE THREAD

**Issue by 2byrds** [roots-id/roots-react-native#48]

**Comment by AlexAndrei98** [comment]
I did some refactoring and packaging the react-native front end is required if we want to use it as a submodule. 
In my test the submodule App component was exported as a react component component and then initialized in the main functional application layer and passed it the event emitter object. To make it work I need to change the way the UI repo is packaged which will make it unusable to develop unless linked to some functionalities!

**Comment by 2byrds** [comment]
cool! lets talk about it at today's meeting.

**Comment by 2byrds** [comment]
Alex is going to fork from roots-react-native to create a prism agent api app to prove this new way.  roots-event-handler/roots-manager will get added to roots-react-native in separate ticket @AlexAndrei98 will create. And generally we believe we will fork from roots-react-native and never add UI updates in our forks.

**Comment by 2byrds** [comment]
@AlexAndrei98 will create a consolidation issue in order to unite roots-react-native-experimental into roots-react-native.
We want to end to end up with the latest UI changes in roots-react-native.
Also create a ticket for RootsWallet UI differences to get added to the new roots-react-native UI.

**Comment by 2byrds** [comment]
I created a single ticket for uniting the UIs for @AlexAndrei98

**Comment by 2byrds** [comment]
I create a ticket to include roots-event-handler in roots-react-native
